OpenConext/OpenConext-manage

manage-server/src/main/java/manage/format/EngineBlockFormatter.java

EngineBlock recently added support for telephone numbers of contacts
in the metadata, see:
https://github.com/OpenConext/OpenConext-engineblock-metadata/commit/7dce82b
In order for this to work, manage should include the number in the
metadata as well - janus already does that.

Support contact telephone number in EngineBlock metadata

---

manage-server/src/main/resources/metadata_export/saml20_sp.xml
manage-server/src/test/resources/xml/expected_metadata_export_saml20_sp.xml
manage-server/src/test/resources/xml/metadata_import_saml20_sp.xml

The UIInfo element is part of SAML:2.0:metadata:ui schema and not the
SAML:2.0:metadata schema. The SP metadata XML now reflects this,
allowing validation using the XSD.

Define mdui extension in SP metadata XML

---

manage-server/src/main/java/manage/shibboleth/ShibbolethPreAuthenticatedProcessingFilter.java

I was missing a displayName and this has proven to be quite difficult to debug.. On the Shibboleth-side everything seems fine, session is succesfully started, etc... On the Manage-side a HTTP basic auth pop-up and no meaningful logging.
I'm sure there's a better way of fixing this, like perhaps showing a meaningful message in the browser and some documentation on the contract, but for now this quick fix should hopefully prevent deployers from banging their head against the wall.
btw, we don't even seem to be using displayName?

Log error message when contract not met

---

manage-server/src/main/java/manage/format/EngineBlockFormatter.java
manage-server/src/test/resources/push/push.expected.json
manage-server/src/test/resources/push/push_results.json

Not the counter i but the actual field "index" should be passed to Engineblock as the Index.

EB formatter: fix ACS index support.

---

manage-server/src/main/java/manage/validations/LocalEmailFormatValidator.java

Ampersands are perfectly legal in email addresses

Update email pattern

---

manage-server/pom.xml

The controllers in Manage use the `@Validated` annotation however, this annotation requires 
```       
<dependency>
<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-starter-validation</artifactId>
</dependency>
```
to work since spring 2.3: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3.0-M1-Release-Notes

Added missing dependency spring-boot-starter-validation

---

manage-gui/pom.xml
manage-server/pom.xml
pom.xml

Streamline the parent pom to release the same version as the GUI and Server, so it makes the release process more clear.

Streamline version numbers used for the modules

---

manage-server/src/main/java/manage/repository/MetaDataRepository.java

Maybe it's dependent on the way I register my SPs, but sometimes the name and displayName are completely different..
For example, for the `name` we usually have a more technical name like "Sharepoint customer X" and then the `displayName` would be a user-friendly name like "Samenwerkruimten"..

Add displayName to search algorithm

---

manage-server/src/main/java/manage/control/DatabaseController.java
manage-server/src/main/java/manage/control/ExportController.java
manage-server/src/main/java/manage/control/MetaDataController.java
manage-server/src/main/java/manage/control/ScopeController.java
manage-server/src/main/java/manage/control/SystemController.java
manage-server/src/main/java/manage/control/UserController.java
manage-server/src/main/java/manage/control/ValidationController.java

Hi all,
We have made changes to some back-end Controller endpoints to require the correct authorisation. Only endpoints that did not have an authorisation check before were updated. The following principle was used to determine the authorisation:
If it's a /client endpoint:
- GET endpoints will check for 'USER'
- POST, PUT endpoints will check for 'ADMIN'
If it's an /internal endpoint
- GET endpoints will check for 'READ'
(POST, PUT have not been found updated as the authorisation check is already present)
This change improves the security by explicitly requiring authorisation for most (the /disclaimer endpoint has been left untouched since it is called directly in index.html) endpoints, this is especially useful for endpoints available to external applications.
Please let us know if you …

Added authorisations for controller endpoints

---

manage-server/src/main/java/manage/control/MetaDataController.java
manage-server/src/main/java/manage/web/WebSecurityConfigurer.java
manage-server/src/test/java/manage/control/MetaDataControllerTest.java

Hi all,
Related to the previous PR on adding authorisations for controller endpoints (https://github.com/OpenConext/OpenConext-manage/pull/73), this one focuses on one specific endpoint which was not returning a forbidden response when the API user did not have the right authorisation. This has been resolved and a unit test has been added to verify this.
@oharsta please also note: this implementation should most likely be reworked with the coming generic solution in WebSecurityConfigurer.java that you already mentioned.

Fixed authorisation for controller endpoint

---

manage-server/src/main/java/manage/service/MetaDataService.java

Hi all,
We have extended the validation of the duplicate entity id check so that it is now the following
- If it is new request and if any entities with that entity id are found
- If one matching record is found and if the ids of the entities do not match   (added)
- if matching records are more than 1
If any of these conditions are met then a duplicate entity id exception is thrown.

Extended duplicate entity id validation

---

manage-gui/src/components/metadata/Connection.jsx
manage-gui/src/components/metadata/SelectState.jsx

Hi all,
We have made some changes so that the possible states for an entity (testaccepted, prodaccepted) are based on the configuration set for that particular entity. For example, the Service Provider state options will now be based on the configuration set in saml20_sp.schema.json.
For us, this makes it possible to introduce a state that is only applicable to a certain entity while not impacting the other entities.
This change should not impact the default behaviour of Manage as there is only testaccepted and prodaccepted for all entities.

Retrieve entity states from configuration

---

manage-server/src/main/java/manage/validations/XMLFormatValidator.java
manage-server/src/test/java/manage/validations/XMLFormatValidatorTest.java

Hi all,
Another finding from our recent pentest is the vulnerability of the XMLFormatValidator to XXE injection. We have implemented a solution in accordance with the OWASP guideline on this page: https://cheatsheetseries.owasp.org/cheatsheets/XML_External_Entity_Prevention_Cheat_Sheet.html
We have opted for the solution that will have consequences for XML metadata including DTD, namely that it will be completely disabled. This solution is described as the safest solution and is acceptable in our case.
If required, we can also share the exact scenario and example XML for reproducing this, either here or via other channels :)
Please let us know if you agree with this approach.

Resolve XXE vulnerability in XML validation

---

manage-gui/src/components/form/Password.jsx
manage-server/src/main/java/manage/hook/MetaDataHookConfiguration.java
manage-server/src/main/java/manage/hook/SecretHook.java
manage-server/src/main/resources/metadata_configuration/oauth20_rs.schema.json
manage-server/src/main/resources/metadata_configuration/oidc10_rp.schema.json
manage-server/src/test/java/manage/hook/SecretHookTest.java
manage-server/src/test/resources/json/meta_data_seed.json

The default BCrypt strength of 10 decreases the performance of the Introspection endpoint with ~60ms. Under heavy load this is becoming a bottle-neck. The Hook to encrypt plain text secrets now used a strength of 5 for Resource Server secrets.

Weaker strength for Resource Servers / Relaying parties secrets

---

manage-server/src/main/java/manage/control/UserController.java

Hi everyone,
This PR relates to the recent pentest, where a remark was made that according to the API permissions only admins could use the logout endpoint. Therefore we changed permission for the user logout endpoint such that users without the ADMIN role are also able to use it.
Please let us know if you agree with this change.

User logout permission in Manage API

---

manage-server/pom.xml
pom.xml
suppressions.xml

This PR updates Spring Boot to the latest 2.x version (2.7.6) and rest-assured to the latest version (5.3.0). Also, the Dependency Check Maven is introduced, which can invoked by enabling the security-updates profiles, such as:
mvn clean install -P security-updates -DskipTests=true -B
See [OpenConext-SSO-Notification](https://github.com/OpenConext/OpenConext-SSO-Notification) for an example to periodically invoke a dependency check pipeline.

Update Spring Boot and rest-assured, added Dependency Check Maven

---

manage-gui/src/components/metadata/Revisions.jsx

Resolved a minor issue where clicking on "Show diffs for all revisions" did not display the diff details after refreshing the revisions page.

Fix show all revisions after page refresh

---

manage-gui/src/components/metadata/AutoRefresh.jsx
manage-gui/src/components/metadata/AutoRefresh.scss
manage-gui/src/locale/en.js
manage-gui/src/pages/Detail.jsx
manage-gui/src/pages/System.jsx
manage-server/src/main/java/manage/conf/Features.java
manage-server/src/main/java/manage/control/ReaperController.java
manage-server/src/main/java/manage/model/MetaData.java
manage-server/src/main/java/manage/model/Revision.java
manage-server/src/main/java/manage/repository/MetaDataRepository.java
manage-server/src/main/java/manage/service/FeatureService.java
manage-server/src/main/java/manage/service/MetaDataService.java
manage-server/src/main/java/manage/service/jobs/MetadataAutoRefreshRunner.java
manage-server/src/main/java/manage/web/WebSecurityConfigurer.java
manage-server/src/main/resources/application.yml
manage-server/src/main/resources/metadata_configuration/saml20_idp.schema.json
manage-server/src/main/resources/metadata_configuration/saml20_sp.schema.json
manage-server/src/main/resources/metadata_templates/saml20_idp.template.json
manage-server/src/main/resources/metadata_templates/saml20_sp.template.json
manage-server/src/test/java/manage/service/jobs/MetaDataAutoRefreshRunner.java
manage-server/src/test/java/manage/util/LogUtils.java
manage-server/src/test/java/manage/util/MemoryAppender.java
manage-server/src/test/resources/test.properties

This PR adds a feature which makes it possible to automatically refresh certain metadata fields for IdPs/SPs based on a metadata import. By default fields that can be updated through this import include "cerdata", "cerdata2" and "cerdata3", although this can be configured by changing the schema.json files. 
A new tab is added for IdPs/SPs that allows for easy configuration of the automatic refresh. For each IdP/SP it is possible to disable automatic refresh entirely, enable it for only a specific set of fields or to enable it for all fields. If automatic refresh is enabled for one or more fields and the IdP/SP has a metadata-url configured, the IdP/SP is included in the automatic metadata refresh with the metadata-url as the import source. If a change in the  an enabled field is detected, …

Automated metadata refresh

---

manage-gui/src/components/metadata/AutoRefresh.jsx
manage-gui/src/components/metadata/AutoRefresh.scss
manage-gui/src/locale/en.js
manage-gui/src/pages/Detail.jsx

In the PR https://github.com/OpenConext/OpenConext-manage/pull/112 a automated metadata refresh feature was created. Part of this PR was a new tab in the frontend for the SP/IdP entities in which this feature could be configured. Some feedback was provided regarding this frontend, solutions to this feedback has been implemented in this PR:
- The option to enable the automated refresh was enabled even if no metadata URL was configured. This did not cause any problems as entities without metadata URL are skipped in the refresh, but it can lead to confusing situations. Now the check-boxes are disabled and a warning is displayed.
- When the new metadata fields were not present in the schema.json file the tab would still be available but trying to open the tab would lead to errors. Now the tab …

Automated metadata refresh frontend improvements

---

manage-server/src/main/java/manage/service/jobs/MetadataAutoRefreshRunner.java

If you have thousands of entities in your database this generates a lot of needless log entries on production. Kept at debug level for development use.

Downgrade metadata auto refresh skip message to 'debug'.

---

manage-server/src/main/java/manage/format/EngineBlockFormatter.java

Currently only shibmb 0-9 are exported; we need more. Increase the limit from 10 to 30.

Increase shibmb range from 10 to 30
